# Generated by Django 3.1.2 on 2021-01-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('idTransacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('dataTransacao', models.DateField(auto_now=True)),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contas')),
            ],
            options={
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
