# Generated by Django 3.1.2 on 2021-01-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('idConta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('limiteSaqueDiario', models.FloatField()),
                ('flagAtivo', models.BooleanField()),
                ('tipoConta', models.IntegerField()),
                ('dataCriacao', models.DateField(auto_now=True)),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas')),
            ],
            options={
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
